###############################################################################
# BASIC SITE META
###############################################################################
remote_theme: thundergolfer/junior-theme        # GitHub-hosted, Pages-safe theme :contentReference[oaicite:0]{index=0}
title:  "Mario • Research, Portfolio & Diary"
author: "Mario"
description: "Biomedical-imaging researcher: projects, code & musings."
url:  "https://mariopasc.github.io/"             # ← change to your username
baseurl: ""                                     # blank for *user* site
email: "mario@example.com"
date_format: "%b %-d, %Y"

###############################################################################
# FEATURES (mirrors Belotti’s production settings)
###############################################################################
show_related_posts:  true
show_post_footers:  true
show_subscribe_cta: true
show_social_icons:  false
ajaxify_contact_form: false
enable_mathjax: true                            # good for LaTeX in research posts :contentReference[oaicite:1]{index=1}
enable_anchorjs: true
extended_fonts: false

###############################################################################
# SOCIAL USERNAMES
###############################################################################
github_username:   MarioPasc
twitter_username:  ratpenant
linkedin_username: mario-pascual-gonzalez

###############################################################################
# CONTENT COLLECTIONS
###############################################################################
collections:
  research:   { output: true, permalink: /research/:path/ }
  diary:      { output: true, permalink: /diary/:title/ }
  portfolio:  { output: true, permalink: /portfolio/:path/ }
  reviews:    { output: true }

###############################################################################
# DEFAULT FRONT-MATTER (uses layouts that *exist* in the theme)
###############################################################################
defaults:
  - scope: { type: research }
    values: { layout: post,      nav_order: 2 }
  - scope: { type: diary    }
    values: { layout: post,      nav_order: 3 }
  - scope: { type: portfolio }
    values: { layout: portfolio, nav_order: 4 }  # portfolio.html exists :contentReference[oaicite:2]{index=2}
  - scope: { type: reviews  }
    values: { layout: post,      nav_order: 5 }

###############################################################################
# BUILD / SEO / ANALYTICS
###############################################################################
markdown: kramdown
permalink: pretty
paginate: 10                                     # blog page size
paginate_path: "/blog/:num/"
plugins:
  - jekyll-remote-theme                          # whitelisted on Pages :contentReference[oaicite:4]{index=4}
  - jekyll-paginate
  - jekyll-sitemap
sass: { compressed: true }
google_analytics: ""                             # add your UA / G-tag or leave blank
exclude: [vendor, node_modules]
kramdown:
  input: GFM
  hard_wrap: false
  gfm_emojis: false
  auto_id_prefix: 
  auto_id_stripping: false
  auto_ids: true
  entity_output: as_char
  footnote_backlink: &#8617;
  footnote_backlink_inline: "false"
  footnote_nr: 1
  footnote_prefix: 
  header_offset: 0
  html_to_native: false
  latex_headers: section,subsection,subsubsection,paragraph,subparagraph,subparagraph
  line_width: 72
  math_engine: mathjax
  parse_block_html: false
  parse_span_html: true
  remove_block_html_tags: true
  remove_line_breaks_for_cjk: false
  remove_span_html_tags: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  template: 
  transliterated_header_ids: false