###############################################################################
# BASIC SITE META
###############################################################################
remote_theme: thundergolfer/junior-theme        # GitHub-hosted, Pages-safe theme :contentReference[oaicite:0]{index=0}
title:  "Mario • Research, Portfolio & Diary"
author: "Mario"
description: "Biomedical-imaging researcher: projects, code & musings."
url:  "https://mariopasc.github.io/"             # ← change to your username
baseurl: ""                                     # blank for *user* site
email: "mario@example.com"
date_format: "%b %-d, %Y"

###############################################################################
# FEATURES (mirrors Belotti’s production settings)
###############################################################################
show_related_posts:  true
show_post_footers:  true
show_subscribe_cta: true
show_social_icons:  false
ajaxify_contact_form: false
enable_mathjax: true                            # good for LaTeX in research posts :contentReference[oaicite:1]{index=1}
enable_anchorjs: true
extended_fonts: false

###############################################################################
# SOCIAL USERNAMES
###############################################################################
github_username:   MarioPasc
twitter_username:  ratpenant
linkedin_username: mario-pascual-gonzalez

###############################################################################
# CONTENT COLLECTIONS
###############################################################################
collections_dir: content

collections:
  blog:
    output: true
    permalink: /blog/:title/
  research:   
    output: true
    permalink: /research/:path/

###############################################################################
# DEFAULT FRONT-MATTER (uses layouts that *exist* in the theme)
###############################################################################
defaults:
  - scope: 
      path: "content/_blog"
    values: 
      layout: post
  - scope: 
      path: "content"
    values: 
      layout: default
  - scope: 
      type: blog
    values: 
      layout: post
  - scope: 
      type: research
    values: 
      layout: post
      nav_order: 2

###############################################################################
# BUILD / SEO / ANALYTICS
###############################################################################
markdown: kramdown
permalink: pretty
paginate: 10                                     # blog page size
paginate_path: "/blog/:num/"
plugins:
  - jekyll-remote-theme                          # whitelisted on Pages :contentReference[oaicite:4]{index=4}
  - jekyll-paginate
  - jekyll-sitemap
sass: 
  style: compressed
google_analytics: ""                             # add your UA / G-tag or leave blank
exclude: [vendor, node_modules]
kramdown:
  input: GFM